# Generated by Django 4.1.13 on 2025-12-09 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=250)),
                ('Dificultad', models.CharField(max_length=100)),
                ('Notas', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=250)),
                ('contenido', models.TextField()),
                ('fuente', models.CharField(max_length=250)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150, unique=True)),
                ('Correo', models.EmailField(max_length=254, unique=True)),
                ('nivel_estudios', models.CharField(max_length=100)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('Dias_Libres', models.TextField()),
                ('periodo_prefencia', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sesiones_Estudios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('duracion', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Materias_id', models.ForeignKey(db_column='materia_id', on_delete=django.db.models.deletion.CASCADE, to='administrador.materias')),
                ('Planes_id', models.ForeignKey(blank=True, db_column='plan_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.planes')),
                ('Usuarios_id', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='administrador.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='planes',
            name='Usuarios_id',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='administrador.usuarios'),
        ),
    ]
