# Generated by Django 6.0 on 2025-12-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_sesiones_estudios_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesiones_estudios',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sesiones_estudios',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
