# Generated by Django 6.0 on 2025-12-18 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_alter_sesiones_estudios_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='Usuarios_id',
            field=models.ForeignKey(db_column='usuario_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='administrador.usuarios'),
            preserve_default=False,
        ),
    ]
